on: [push]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: SQAaaS assessment action
        uses: eosc-synergy/sqaaas-assessment-action@v1
        with:
          repo: 'https://github.com/eosc-synergy/sqaaas-reporting'
          branch: 'main'
